Add MAF Complete data type
mskcc/smile-server pull request #1095
Opened 2024-02-13 16:02 UTC by qu8n

# HERA Sample Tracker Support: MAF Complete

General updates:
- Defined a new MafComplete class
- Defined Tempo's relationship with MafComplete and provided Tempo class functions to interact with MafComplete
- Defined Neo4j queries to get MafComplete data
- Modified the Tempo message handler to be able to handle MafComplete events 
- Added mocked test data

---
## Crossing T's and dotting I's

Please follow these checklists to help prevent any unexpected issues from being introduced by the changes in this pull request. If an item does not apply then indicate so by surrounding the line item with `~~` to strikethrough the text. See [basic writing and formatting syntax](https://docs.github.com/en/github/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax) for more information.

### I. Web service and data model checklist

Please follow these checks if any changes were made to any classes in the web, service, or persistence layers.

**Data checks:**
Updates were made to the mocked incoming request data and/or mocked published request data:
- [x] [smile-server test data](https://github.com/mskcc/smile-server/tree/master/service/src/test/resources/data)
- [ ] [smile-commons test data](https://github.com/mskcc/smile-commons/tree/master/src/test/resources/data)
- [ ] [smile-label-generator test data](https://github.com/mskcc/smile-label-generator/tree/master/src/test/resources/data)
- [ ] [smile-request-filter test data](https://github.com/mskcc/smile-request-filter/tree/master/src/test/resources/data)

**Code checks:**
- [ ] Endpoints were tested to ensure their integrity.
- [ ] Screenshots have been provided to demonstrate changes made to the response body JSON schema and/or swagger page.
- [x] Unit tests were updated in relation to updates to the mocked test data.

### II. Neo4j models and database schema checklist:
- [x] Neo4j persistence models were changed.
- [ ] The graph database produces the expected changes to models, relationships, and/or property names. [provide screenshot of updated elements in graph db below]

### III. Message handlers checklist:
- [x] Changes in this PR affect the workflow of incoming messages.
- [ ] Messages are following the expected workflow when published to the topic(s) changed or introduced in this pull request.
- [x] Unit tests were added to ensure messages are handled as expected.

If no unit tests were updated or added, then please explain why: [insert details here]

Please describe how the workflow and messaging was tested/simulated:

**Describe your testing environment:**

- NATS [local, local docker, dev server, production]
- Neo4j [local, local docker, dev server, production]
- SMILE Server [local, local docker, dev server, production]
- Message publishing simulation [nats cli, docker nats cli, smile publisher tool, other (describe below)]

Other: [insert details on how messages were published or simulated for testing]

### IV. Configuration and/or permissions checklist:
- [x] New topics were introduced.
- [x] The topics and appropriate permissions were updated in [cmo-metadb-configuration](https://github.mskcc.org/cmo/cmo-metadb-configuration).
- [ ] If applicable, a new account was set up and the account credentials and keys are checked into [cmo-metadb-configuration](https://github.mskcc.org/cmo/cmo-metadb-configuration).
- [ ] Account credentials and keys were shared with the appropriate parties.

---
### Screenshots

---
### General checklist:
- [ ] All requested changes and comments have been resolved.
- [x] The commit log is comprehensible. It follows [7 rules of great commit messages](http://chris.beams.io/posts/git-commit/). For most PRs a single commit should suffice, in some cases multiple topical commits can be useful. During review it is ok to see tiny commits (e.g. Fix reviewer comments), but right before the code gets merged to master or rc branch, any such commits should be squashed since they are useless to the other developers. Definitely avoid [merge commits, use rebase instead.](http://nathanleclaire.com/blog/2014/09/14/dont-be-scared-of-git-rebase/)

2024-02-13 17:24 UTC, qu8n commented
@ao508 Just requesting your review for now. I'll wait to merge it after your review and after rebasing it when your QcComplete work is merged.

Whenever we meet, could we walk through the checkboxes of `smile-server`'s PR description template again? Thank you.

2024-02-13 17:43 UTC, qu8n commented on model/src/main/java/org/mskcc/smile/model/tempo/MafComplete.java
> +        this.normalPrimaryId = normalPrimaryId;
Note that while the incoming JSON names this property `normal_primaryId`, I'm renaming it using camel case to fit Java's naming convention.

2024-02-13 20:05 UTC, ao508 commented on service/src/main/java/org/mskcc/smile/service/impl/TempoMessageHandlingServiceImpl.java
> +                            mafCompleteMap.get("normal_primaryId"),
update

2024-02-13 20:07 UTC, ao508 reviewed
TODO: already discussed making updates to `normal_primaryId` -> `normalPrimaryId`

2024-02-14 16:48 UTC, ao508 requested changes
there are some very small stylistic changes to fix but the code itself is good to go

once updated please feel free to merge the PR yourself

2024-02-14 16:48 UTC, ao508 commented on model/src/main/java/org/mskcc/smile/model/tempo/Tempo.java
> +         * Returns list of maf complete events.
indentation

2024-02-14 16:48 UTC, ao508 commented on service/src/main/java/org/mskcc/smile/service/impl/TempoMessageHandlingServiceImpl.java
> +
extra new line

2024-02-14 16:48 UTC, ao508 commented on service/src/main/java/org/mskcc/smile/service/impl/TempoMessageHandlingServiceImpl.java
> +
extra newline

2024-02-14 17:02 UTC, qu8n commented on model/src/main/java/org/mskcc/smile/model/tempo/Tempo.java
> +         * Returns list of maf complete events.
Nice catch. Thank you

2024-02-14 17:03 UTC, merged